CREATE DATABASE IF NOT EXISTS visionvend;
USE visionvend;

CREATE TABLE IF NOT EXISTS inventory (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_name VARCHAR(255) NOT NULL UNIQUE,
  quantity INT NOT NULL DEFAULT 0,
  last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alerts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_name VARCHAR(255) NOT NULL,
  current_stock INT NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'LOW STOCK', -- 'LOW STOCK', 'OUT OF STOCK', 'RESOLVED'
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
